# Generated by Django 4.0.5 on 2022-06-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panstwo', models.CharField(max_length=50, unique=True)),
                ('miasto', models.CharField(max_length=50, unique=True)),
                ('kod', models.CharField(max_length=12, unique=True)),
                ('ulica', models.CharField(max_length=50, unique=True)),
                ('budynek', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=50, unique=True)),
                ('producent', models.CharField(max_length=50, unique=True)),
                ('wydawca', models.CharField(max_length=50, unique=True)),
                ('ocena', models.PositiveSmallIntegerField(default=0)),
                ('premiera', models.DateField(blank=True, null=True)),
                ('opis', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Gra_gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gra', models.CharField(max_length=50, unique=True)),
                ('gatunek', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gra_polka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gra', models.CharField(max_length=50, unique=True)),
                ('polka', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('strona', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wydawca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('strona', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
            ],
        ),
    ]
