# Generated by Django 4.0.5 on 2022-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='kod',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='adres',
            name='miasto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adres',
            name='panstwo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adres',
            name='ulica',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gra',
            name='producent',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gra',
            name='wydawca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gra_gatunek',
            name='gatunek',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gra_gatunek',
            name='gra',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gra_polka',
            name='gra',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gra_polka',
            name='polka',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='polka',
            name='nazwa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producent',
            name='nazwa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wydawca',
            name='nazwa',
            field=models.CharField(max_length=50),
        ),
    ]
