# Generated by Django 4.0.5 on 2022-06-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_alter_producent_adres_alter_wydawca_adres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gra',
        ),
    ]
